global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "thairag"
    metrics_path: /metrics
    static_configs:
      - targets: ["thairag:8080"]
        labels:
          instance: "thairag-api"
