import { Row, Col, Card, Statistic, Typography, Tag, Descriptions, Spin, Tooltip, Empty } from 'antd';
import {
  DollarOutlined,
  ThunderboltOutlined,
  FileTextOutlined,
  QuestionCircleOutlined,
  CloudOutlined,
} from '@ant-design/icons';
import { useQuery } from '@tanstack/react-query';
import { getUsageStats } from '../api/settings';
import { useMetrics } from '../hooks/useHealth';
import { parsePrometheusMetric } from '../api/metrics';

const PROVIDER_LABELS: Record<string, string> = {
  ollama: 'Ollama (Local)',
  claude: 'Anthropic Claude',
  openai: 'OpenAI',
  open_ai: 'OpenAI',
  open_ai_compatible: 'OpenAI-Compatible (Local)',
  gemini: 'Google Gemini',
  fastembed: 'FastEmbed (Local)',
  cohere: 'Cohere',
};

function providerLabel(kind: string): string {
  return PROVIDER_LABELS[kind] ?? kind;
}

function isLocalProvider(kind: string): boolean {
  return ['ollama', 'open_ai_compatible', 'fastembed'].includes(kind);
}

function formatTokenCount(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(2)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return n.toLocaleString();
}

export function UsagePage() {
  const usage = useQuery({
    queryKey: ['usage-stats'],
    queryFn: getUsageStats,
    refetchInterval: 30_000,
  });

  const metrics = useMetrics();
  const metricsText = metrics.data || '';
  const httpRequests = parsePrometheusMetric(metricsText, 'http_requests_total');
  const activeSessions = parsePrometheusMetric(metricsText, 'active_sessions_total');

  const data = usage.data;
  const isLocal = data ? isLocalProvider(data.llm_kind) : false;

  return (
    <>
      <Typography.Title level={4}>Usage & Costs</Typography.Title>

      {usage.isLoading ? (
        <div style={{ textAlign: 'center', padding: 40 }}><Spin /></div>
      ) : !data ? (
        <Empty description="Failed to load usage data" />
      ) : (
        <>
          {/* Cost summary */}
          <Row gutter={[16, 16]}>
            <Col xs={24} sm={12} lg={6}>
              <Card>
                <Statistic
                  title={
                    <Tooltip title="Total cost estimated from cumulative token usage and current model pricing. Only applies to cloud providers (Claude, OpenAI, Gemini). Local models (Ollama) are free.">
                      <span>Estimated Cost <QuestionCircleOutlined /></span>
                    </Tooltip>
                  }
                  value={
                    data.estimated_cost_usd === null
                      ? 'N/A'
                      : data.estimated_cost_usd === 0
                        ? 'Free (Local)'
                        : `$${data.estimated_cost_usd.toFixed(4)}`
                  }
                  prefix={<DollarOutlined />}
                  valueStyle={{
                    color: isLocal ? '#52c41a' : data.estimated_cost_usd && data.estimated_cost_usd > 1 ? '#cf1322' : undefined,
                  }}
                />
              </Card>
            </Col>
            <Col xs={24} sm={12} lg={6}>
              <Card>
                <Statistic
                  title={
                    <Tooltip title="Total LLM tokens consumed since first use. Includes both prompt tokens (input) and completion tokens (output). Persisted across restarts.">
                      <span>Total Tokens <QuestionCircleOutlined /></span>
                    </Tooltip>
                  }
                  value={formatTokenCount(data.total_tokens)}
                  prefix={<ThunderboltOutlined />}
                />
              </Card>
            </Col>
            <Col xs={24} sm={12} lg={6}>
              <Card>
                <Statistic
                  title={
                    <Tooltip title="Tokens sent to the LLM as input (system prompt + context chunks + user messages). Typically the larger portion of usage.">
                      <span>Prompt Tokens <QuestionCircleOutlined /></span>
                    </Tooltip>
                  }
                  value={formatTokenCount(data.prompt_tokens)}
                  prefix={<FileTextOutlined />}
                />
              </Card>
            </Col>
            <Col xs={24} sm={12} lg={6}>
              <Card>
                <Statistic
                  title={
                    <Tooltip title="Tokens generated by the LLM as output (the answer). Usually billed at a higher rate than prompt tokens.">
                      <span>Completion Tokens <QuestionCircleOutlined /></span>
                    </Tooltip>
                  }
                  value={formatTokenCount(data.completion_tokens)}
                  prefix={<FileTextOutlined />}
                />
              </Card>
            </Col>
          </Row>

          {/* Provider details */}
          <Card style={{ marginTop: 16 }} title="Provider Configuration">
            <Descriptions column={{ xs: 1, sm: 2 }} bordered size="small">
              <Descriptions.Item label="LLM Provider">
                <Tag icon={<CloudOutlined />} color={isLocal ? 'green' : 'blue'}>
                  {providerLabel(data.llm_kind)}
                </Tag>
              </Descriptions.Item>
              <Descriptions.Item label="LLM Model">
                <Tag>{data.llm_model}</Tag>
              </Descriptions.Item>
              <Descriptions.Item label="Embedding Provider">
                <Tag icon={<CloudOutlined />} color={isLocalProvider(data.embedding_kind) ? 'green' : 'blue'}>
                  {providerLabel(data.embedding_kind)}
                </Tag>
              </Descriptions.Item>
              <Descriptions.Item label="Embedding Model">
                <Tag>{data.embedding_model}</Tag>
              </Descriptions.Item>
            </Descriptions>

            {isLocal && (
              <Typography.Paragraph type="secondary" style={{ marginTop: 12, marginBottom: 0 }}>
                You are using a local LLM provider. No API costs are incurred. Token counts are still tracked for monitoring purposes.
              </Typography.Paragraph>
            )}

            {!isLocal && data.estimated_cost_usd !== null && (
              <Typography.Paragraph type="secondary" style={{ marginTop: 12, marginBottom: 0 }}>
                Cost estimates are approximate and based on publicly listed API pricing. Actual billing may vary depending on your plan, volume discounts, or cached tokens.
              </Typography.Paragraph>
            )}
          </Card>

          {/* Session metrics */}
          <Card style={{ marginTop: 16 }} title="Session Metrics (Since Last Restart)">
            <Row gutter={[16, 16]}>
              <Col xs={12} sm={8}>
                <Statistic title="HTTP Requests" value={httpRequests} />
              </Col>
              <Col xs={12} sm={8}>
                <Statistic title="Active Sessions" value={activeSessions} />
              </Col>
            </Row>
          </Card>

          {/* Pricing reference */}
          {!isLocal && (
            <Card style={{ marginTop: 16 }} title="Pricing Reference (per 1M tokens)">
              <Typography.Paragraph type="secondary" style={{ marginBottom: 8 }}>
                Approximate pricing for common models. Your active model is highlighted.
              </Typography.Paragraph>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
                <thead>
                  <tr style={{ borderBottom: '1px solid #333' }}>
                    <th style={{ textAlign: 'left', padding: '4px 8px' }}>Model</th>
                    <th style={{ textAlign: 'right', padding: '4px 8px' }}>Input</th>
                    <th style={{ textAlign: 'right', padding: '4px 8px' }}>Output</th>
                  </tr>
                </thead>
                <tbody>
                  {PRICING_TABLE.map((row) => {
                    const isActive = data.llm_model.includes(row.match);
                    return (
                      <tr
                        key={row.model}
                        style={{
                          borderBottom: '1px solid #222',
                          fontWeight: isActive ? 'bold' : undefined,
                          background: isActive ? 'rgba(24, 144, 255, 0.1)' : undefined,
                        }}
                      >
                        <td style={{ padding: '4px 8px' }}>
                          {row.model} {isActive && <Tag color="blue" style={{ marginLeft: 4 }}>active</Tag>}
                        </td>
                        <td style={{ textAlign: 'right', padding: '4px 8px' }}>${row.input}</td>
                        <td style={{ textAlign: 'right', padding: '4px 8px' }}>${row.output}</td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </Card>
          )}
        </>
      )}
    </>
  );
}

const PRICING_TABLE = [
  { model: 'Claude Opus', match: 'opus', input: '15.00', output: '75.00' },
  { model: 'Claude Sonnet', match: 'sonnet', input: '3.00', output: '15.00' },
  { model: 'Claude Haiku', match: 'haiku', input: '0.25', output: '1.25' },
  { model: 'GPT-4o', match: 'gpt-4o', input: '2.50', output: '10.00' },
  { model: 'GPT-4o Mini', match: 'gpt-4o-mini', input: '0.15', output: '0.60' },
  { model: 'GPT-4 Turbo', match: 'gpt-4-turbo', input: '10.00', output: '30.00' },
  { model: 'Gemini Pro', match: 'pro', input: '1.25', output: '5.00' },
  { model: 'Gemini Flash', match: 'flash', input: '0.075', output: '0.30' },
];
